### ISSUE TITLE
Publish a new version

### ISSUE THREAD

**Issue by mrpham** [Akylas/mobile-sdk#1]
I appreciate your contribution to this SDK, i also really love it and feel sad that CartoDB doesn't have any more updates for a long time.

Are you planning to publish a separate version from this fork? If there is, I hope to see it soon, 

Thank you very much.

**Comment by farfromrefug** [comment]
@mrpham I should be clearer. We had some discussions with the old Dev about creating a new framework. I truly believe this framework is crazy strong, much stronger than most (except for the  styling part) and that it would deserve to be maintained. We had many ideas for new features like 3d map, splitting the framework so that you only get what you need, layers to mix vector/raster... But all that requires a lot of work and the old Dev has a full time job.
So for this to work we would need funding to support the old Dev (not me!)
If some parties (companies maybe) were interested (which is why I drop it here) it could become a thing. 

PS: I have a dream this could become the official OSM framework for mobile/desktop(web in the future?)

**Comment by farfromrefug** [comment]
@mrpham if you want to test i just published a rc build of my fork https://github.com/Akylas/mobile-sdk/releases/tag/v5.0.0-rc.1. Not released on maven/cocoapod yet. I need to find a new framework name first...

**Comment by mrpham** [comment]
> @mrpham if you want to test i just published a rc build of my fork https://github.com/Akylas/mobile-sdk/releases/tag/v5.0.0-rc.1. Not released on maven/cocoapod yet. I need to find a new framework name first... WARNING: all carto online stuff + licensing have been removed.

@farfromrefug , many thanks.

**Comment by mrpham** [comment]
@farfromrefug , I tested your v5.0.0-rc1 build. It works fine, I haven't encountered any issues. Thanks again for your contributions

Also, I would like to ask if this v5.0.0-rc1 build supports "16 KB page sizes" as stated by Google? (https://developer.android.com/guide/practices/page-sizes?hl=en)

Thank you.

**Comment by farfromrefug** [comment]
@mrpham from a quick reading I would need to use latest ndk which might require a bit of work. But you could still test using the described instructions on a 16kb emulator. I will look at it

On a side note if you want to help me and possibly @mtehver, please consider sponsoring me. For now it is my personal sponsor page, but if more people want that project to grow we will setup an organization.

**Comment by farfromrefug** [comment]
@mrpham 16kb page size is now supported in latest published versions!
